stages:
  - test
  - deploy

image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install

test:
  image: node:latest
  stage: test
  tags:
    - docker
  script:
    - npm test

deploy:
  image: node:latest
  stage: deploy
  tags:
    - docker
  script:
    - CI=false npm run-script build
    - rm -rf public
    - mv build public
  only:
    - master # run on master branch
